spring:
  config:
    import: optional:classpath:application-oauth.yml
  profiles:
    active: dev
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:3600000}

